### ISSUE TITLE
[bug] highD_generate_scenarios.m has some errors

### ISSUE THREAD

**Issue by dublinsky** [lab176344/Traffic_Sceanrios-VoteBasedEVT#1]
env: matlab 2020a
operation: uncomment the following paragraph and run 'script_high_D_scenario.m':
''
% Generate OGs
ogLeftCutOut = generateOccupancy(scenario_leftcutout);
ogLaneLeft = generateOccupancy(scenario_lnchangeleft);
ogLaneRight = generateOccupancy(scenario_lnchangeright);
ogFoll = generateOccupancy(scenario_following(1:1000));
ogFollAcc = generateOccupancy(scenario_followingacc);
ogFollDec = generateOccupancy(scenario_followingdec);
ogLeftCut = generateOccupancy(scenario_leftcutin);
ogRightCut = generateOccupancy(scenario_rightcutin);
ogRightCutOut = generateOccupancy(scenario_rightcutout);
save('HighDScenario.mat','ogLeftCutOut','ogLaneLeft',...
    'ogLaneRight','ogFoll','ogFollAcc','ogFollDec',...
    'ogLeftCut','ogRightCut','ogRightCutOut');
'', pass;
run 'data_prepare_save.m', pass;
then run 'prepare_openset_data.m', and obtain the following error:
"
位置 1 处的索引超出数组边界(不能超出 42)。

出错 prepare_openset_data (line 18)
X_train = [ogLaneRight(1:400,:,:,:)];
"
check the dimension of 'ogLaneRight' using disp(size(ogLaneRight)), we obtain:
42    30   200    10

**Comment by lab176344** [comment]
Sorry for the late response. I will check locally and get back

**Comment by lab176344** [comment]
@dublinsky are you using the full highD data? I am not able to replicate your error. ogLaneRight has the size of 650 in my case
